Fix for: Producer JSON format example
This is a small fix for the documentation - for the producer json format example after I have tried it.
I have added .build() to the json example since without it you get the following exception:
error: incompatible types: JsonDataWithSchemaBuilder cannot be converted to JsonDataWithSchema